version: "3.7"

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - 8002:80
        networks:
          - crawler_database

networks:
  crawler_database:
    name: crawler_database

